
<div class="container my-5 text-center px-lg-5">
    <div class="h2 mb-5">O aplikaci</div>
    <p class="mt-5 fs-5 mx-3 mx-lg-5">
        Tato aplikace byla vytvořena jako <strong>projekt k závěrečné zkoušce</strong> rekvalifikačního kurzu <em>"Programátor WWW aplikací (PHP)"</em>.
    </p>
    <p class="mt-5 fs-6 mx-3 mx-lg-5">
        Obsahuje kompletní <strong>správu pojištěných a jejich pojištění</strong> (včetně jejich přidání, zobrazení, editace či odstranění)
    </p>
    <p class="mt-5 fs-6 mx-3 mx-lg-5">
        Aplikace dále rozlišuje <strong>uživatelské role pojištěného a administrátora</strong>, přičemž právě dle tohoto rozdělení <strong>uzpůsobuje viditelný obsah obsah</strong>.
    </p>
</div>