    <div class="container py-5">
        <div class="row">
            <div class="col text-center">
                <div class="h2 mb-5"><?= $pojisteni['nazev'] ?></div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center mb-3">
            <div class="col-md-4 col-lg-3 text-center">
                <div class="h5">Částka:</div>
                <ul class="list-unstyled my-3">
                    <li><?= $pojisteni['castka'] ?> Kč</li>
                </ul>
            </div>
            <div class="col-md-4 col-lg-3 text-center">
                <div class="h5">Předmět pojištění:</div>
                <ul class="list-unstyled my-3">
                    <li><?= $pojisteni['predmet'] ?></li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center align-items-center mb-3">
            <div class="col-md-4 col-lg-3 text-center">
                <div class="h5">Platnost od:</div>
                <ul class="list-unstyled my-3">
                    <li><?= date("d. m. Y", strtotime($pojisteni['platnost_od'])) ?></li>
                </ul>
            </div>
            <div class="col-md-4 col-lg-3 text-center">
                <div class="h5">Platnost do:</div>
                <ul class="list-unstyled my-3">
                    <li><?= date("d. m. Y", strtotime($pojisteni['platnost_do'])) ?></li>
                </ul>
            </div>
        </div>
        <?php if ($_SESSION["pojistenec"]['admin']) : ?>
        <div class="row justify-content-center">
            <div class="col-auto">
                <a class="btn btn-warning" href="pojistenci/<?= $pojistenci_id ?>/<?= $pojisteni['pojisteni_id'] ?>/editovatPojisteni" role="button">Upravit pojištění</a>
            </div>
        </div> 
        <?php endif ?>
    </div>
