<div class="container py-5">
    <h3 class="text-center">Změna hesla</h3>
</div>

<div class="container mb-5">
    <form method="post">
        <div class="row justify-content-center mb-3">
            <label for="soucasneHeslo" class="col-md-3 col-lg-2 col-form-label">Současné heslo</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="soucasneHeslo" name="soucasneHeslo">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <label for="noveHeslo" class="col-md-3 col-lg-2 col-form-label">Nové heslo</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="noveHeslo" name="noveHeslo">
            </div>
        </div>
        <div class="row justify-content-center mb-5">
            <label for="noveHesloZnovu" class="col-md-3 col-lg-2 col-form-label">Nové heslo znovu</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="noveHesloZnovu" name="noveHesloZnovu">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <button type="submit" class="btn btn-primary col-auto">Změnit heslo</button>
        </div>
    </form>
</div>
