<div class="container py-5">
    <h3 class="text-center">Nastavení hesla</h3>
</div>

<div class="container mb-5">
    <form method="post">
        <div class="row justify-content-center mb-3">
            <label for="email" class="col-md-3 col-lg-2 col-form-label">E-mail</label>
            <div class="col-md-4 col-lg-3">
                <input type="email" class="form-control" id="email" name="email">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <label for="heslo" class="col-md-3 col-lg-2 col-form-label">Heslo</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="heslo" name="heslo">
            </div>
        </div>
        <div class="row justify-content-center mb-5">
            <label for="hesloZnovu" class="col-md-3 col-lg-2 col-form-label">Heslo znovu</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="hesloZnovu" name="hesloZnovu">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <button type="submit" class="btn btn-primary col-auto">Nastavit heslo</button>
        </div>
    </form>
</div>
