
<div class="container py-5">
    <div class="row justify-content-between align-items-center mb-3">
        <div class="col-auto h2">Pojištěnci</div>
        <div class="col-auto">
            <a class="btn btn-primary" href="pojistenci/pridat" role="button">Přidat pojištěnce</a>
        </div>
    </div>
    <table class="table table-hover align-middle">
        <thead>
            <tr>
                <th scope="col">Jméno</th>
                <th scope="col">Bydliště</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($pojistenci as $pojistenec) : ?>
                <tr>
                    <td scope="row"><a href="pojistenci/<?= $pojistenec['pojistenci_id'] ?>"><?= $pojistenec['jmeno'] . " " . $pojistenec['prijmeni'] ?></a></td>
                    <td class="w75"><?= $pojistenec['ulice'] . " " . $pojistenec['cislo_popisne'] . ", " . $pojistenec['mesto'] ?></td>
                    <td class="text-end w-25">
                        <a class="btn btn-warning mx-lg-3 mb-1 mb-lg-0" href="pojistenci/<?= $pojistenec['pojistenci_id'] ?>/editovat" role="button">Editovat</a>
                        <a class="btn btn-danger mt-1 mt-lg-0" href="pojistenci/<?= $pojistenec['pojistenci_id'] ?>/odstranit" role="button">Odstranit</a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
    