<div class="container my-5">
    <div class="row">
        <div class="col text-center">
             <div class="h2 mb-5">Nabídka pojištění</div>
        </div>
    </div>
    <div class="row justify-content-center align-items-center text-center mx-1 mx-md-0">
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="py-5 px-2">Životní pojištění</p>
        </div>
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="m-2 py-5 px-2">Cestovní pojištění</p>
        </div>
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="m-2 py-5 px-2">Pojištění vozidla</p>
        </div>
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="m-2 py-5 px-2">Pojištění majetku</p>
        </div>
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="m-2 py-5 px-2">Pojištění odpovědnosti</p>
        </div>
        <div class="col-md-4 col-lg-3 rounded m-3 bg-secondary text-light h2 py-lg-3 p-xl-5">
            <p class="m-2 py-5 px-2">Pojištění mazlíčků</p>
        </div>
    </div>
</div>
