<div class="container py-5">
    <h3 class="text-center">Přihlášení do klientské sekce</h3>
</div>

<div class="container mb-5">
    <form method="post">
        <div class="row justify-content-center mb-3">
            <label for="prihlaseniEmail" class="col-md-2 col-lg-1 col-form-label">E-mail</label>
            <div class="col-md-4 col-lg-3">
                <input type="email" class="form-control" id="prihlaseniEmail" name="email">
            </div>
        </div>
        <div class="row justify-content-center mb-5">
            <label for="prihlaseniHeslo" class="col-md-2 col-lg-1 col-form-label">Heslo</label>
            <div class="col-md-4 col-lg-3">
                <input type="password" class="form-control" id="prihlaseniHeslo" name="heslo">
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <button type="submit" class="btn btn-primary col-auto">Přihlásit</button>
        </div>
    </form>
</div>

<p class="text-center">Jedná-li se o Vaše první přihlášení po registraci na pobočce, musíte si nejprve <a href="prihlaseni/nastavHeslo">nastavit heslo</a>.</p>

<p class="text-center">Pokud ještě nemáte účet, <a href="registrace">zaregistrujte se</a>.</p>
