<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localproject" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" />
        <link rel="stylesheet" href="styl.css" type="text/css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    </head>

    <body class="bg-light">
        
        <nav class="navbar navbar-expand-md bg-dark navbar-dark px-md-5 py-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ms-1" id="navbarTogglerDemo01">
                    <a class="navbar-brand text-light me-1 me-md-5" href="uvod">Pojištění App</a>
                    <ul class="navbar-nav me-auto ms-md-5">
                        <li class="nav-item me-3">
                            <a class="nav-link active" aria-current="page" href="pojisteni">Pojištění</a>
                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link active" aria-current="page" href="aplikace">O aplikaci</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Můj účet
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <?php if (!isset($_SESSION["pojistenec"])) : ?>
                                    <li><a class="dropdown-item" href="prihlaseni">Přihlášení</a></li>
                                    <li><a class="dropdown-item" href="registrace">Registrace</a></li>
                                <?php else : ?>
                                    <li><a class="dropdown-item" href="profil">Můj profil</a></li>
                                    <?php if (($_SESSION["pojistenec"]["admin"])) : ?>
                                    <li><a class="dropdown-item" href="pojistenci">Pojištěnci</a></li>
                                    <?php else : ?>
                                    <?php endif ?>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="profil/odhlasit">Odhlásit</a></li>
                                <?php endif ?>
                            </ul>                            
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <?php foreach ($zpravy as $zprava) : ?>
            <div class="alert alert-success rounded-0" role="alert"><?= $zprava ?></div>
        <?php endforeach ?>
        <?php foreach ($vyjimky as $vyjimka) : ?>
            <div class="alert alert-danger rounded-0" role="alert"><?= $vyjimka ?></div>
        <?php endforeach ?>
        
        <article>
            <?php $this->kontroler->vypisPohled(); ?>
        </article>
            
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        
    </body>
</html>


