<div class="container d-flex justify-content-center my-5">
    <div class="bg-secondary pozadi-sede d-flex justify-content-center align-items-center">
        <a class="pozadi-citat d-flex flex-column justify-content-center align-items-center text-decoration-none" href="pojisteni">
            <div class="h1 text-light text-center text-citat pt-3">„Minulost hoď za hlavu, žij přítomností, ale mysli na budoucnost.“</div>
            <div class='line mb-5 mt-3'></div>
            <div class="h2 text-light text-center text-citat pt-5">My Vám s tím pomůžeme!</div>
        </a>
    </div>
</div>

